import { Activity, ArrowUpRight, CircleHelp, DoorClosed, Disc3, Layers3, ShieldCheck } from 'lucide-react';
import type { ReactNode } from 'react';
import type { Status } from '@/lib/types';
import { colors, number, statusLabel } from '@/lib/utils';

export function StatusBadge({status,compact=false}:{status:Status;compact?:boolean}) {return <span className={`status-badge ${status} ${compact?'small':''}`}><i/>{statusLabel[status]}</span>;}
export function Panel({title,eyebrow,action,children,className=''}:{title?:string;eyebrow?:string;action?:ReactNode;children:ReactNode;className?:string}) {return <section className={`glass-panel ${className}`}>{title&&<div className="panel-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2></div>{action}</div>}{children}</section>;}
export function EmptyState({title,children,icon}:{title:string;children:ReactNode;icon?:ReactNode}) {return <div className="empty-state"><div className="empty-icon">{icon||<ShieldCheck size={27}/>}</div><h3>{title}</h3><p>{children}</p></div>;}
export function Loading({label='Reading the evidence…'}:{label?:string}) {return <div className="loading-state" role="status"><span className="loader"/><span>{label}</span></div>;}
export function Metric({label,value,detail,icon,status,children}:{label:string;value:number|null;detail:string;icon:ReactNode;status?:Status;children?:ReactNode}) {return <div className={`metric-card glass-panel ${status||''}`}><div className="metric-label">{label}<span className="metric-icon" style={status?{color:colors[status]}:{}}>{icon}</span></div><div className="metric-value">{number(value)}<span className="metric-unit">trainsets</span>{children}</div><div className="metric-detail">{status&&<i style={{background:colors[status]}}/>}{detail}</div></div>;}
export function SectionHeading({eyebrow,title,description,actions}:{eyebrow:string;title:string;description:string;actions?:ReactNode}) {return <div className="section-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}<span className="title-dot">.</span></h1><p>{description}</p></div>{actions&&<div className="heading-actions">{actions}</div>}</div>;}
export function ScoreRing({value,status,size=100}:{value:number|null;status:Status;size?:number}) {const r=42,c=2*Math.PI*r;return <div className="score-ring" style={{width:size,height:size}}><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r={r} fill="none" stroke="rgba(255,255,255,.07)" strokeWidth="5"/><circle cx="50" cy="50" r={r} fill="none" stroke={colors[status]} strokeWidth="5" strokeLinecap="round" strokeDasharray={`${((value??0)/100)*c} ${c}`} transform="rotate(-90 50 50)"/></svg><div><strong>{number(value)}</strong><span>risk index</span></div></div>;}
export function Note({children}:{children:ReactNode}) {return <div className="method-note"><CircleHelp size={14}/><span>{children}</span></div>;}
export function TextLink({children,onClick}:{children:ReactNode;onClick:()=>void}) {return <button className="text-link" onClick={onClick}>{children}<ArrowUpRight size={15}/></button>;}
export function ComponentGlyph({component,size=18}:{component:string;size?:number}) {return component==='bogies'?<Layers3 size={size}/>:component==='doors'?<DoorClosed size={size}/>:component==='brakes'?<Disc3 size={size}/>:<Activity size={size}/>;}
