'use client';
import { useState } from 'react';
import { Activity, ArrowUpRight, Clock3, Gauge, Microscope, Waves } from 'lucide-react';
import type { Detail } from '@/lib/types';
import { componentLabel, number, time } from '@/lib/utils';
import { EmptyState, Note, Panel, ScoreRing, StatusBadge, TextLink } from '@/components/ui';
import { SensorChart, Sparkline } from '@/components/Charts';

export default function Analysis({detail,onExplain,onMaintain}:{detail:Detail;onExplain:()=>void;onMaintain:()=>void}) {const [chosen,setChosen]=useState<string|null>(null);const feature=detail.features.find(f=>f.key===chosen)||detail.features.find(f=>!['speed_kmh','ambient_temp_c'].includes(f.key))||detail.features[0];return <>
<div className="analysis-grid"><Panel title={feature?.label||'Sensor telemetry'} eyebrow="Signal exploration" action={<span className="quiet-chip"><Waves size={13}/>{number(detail.observations)} observations</span>} className="telemetry-panel"><div className="sensor-tabs" role="group" aria-label="Sensor to plot">{detail.features.map(f=><button key={f.key} className={feature?.key===f.key?'active':''} onClick={()=>setChosen(f.key)}>{f.label}</button>)}</div><div className="signal-reading"><div><strong>{number(feature?.latest,2)}<small>{feature?.unit}</small></strong><span>Reading at evidence timestamp · {time(detail.evidence_time,true)} UTC</span></div><div className="baseline-value"><span>Reference median</span><strong>{number(feature?.baseline,2)} <small>{feature?.unit}</small></strong></div></div>{feature?<SensorChart points={detail.points} feature={feature}/>:<EmptyState title="No usable sensor values">The dataset needs valid numeric observations for this component.</EmptyState>}<div className="panel-footnote"><Clock3 size={13}/>{detail.onset?`First detected monitoring anomaly: ${time(detail.onset,true)} UTC`:'No detected anomaly onset in this monitoring window'}</div></Panel>
<Panel title="Condition assessment" eyebrow={componentLabel[detail.component]||detail.component} className="assessment-panel"><div className="assessment-score"><ScoreRing value={detail.risk} status={detail.status}/><div><StatusBadge status={detail.status}/><p>{detail.anomaly_count} flagged observations<br/>in the monitoring window</p></div></div><div className="assessment-insight"><span className="insight-icon"><Microscope size={17}/></span><div><h3>{detail.explanation.title}</h3><p>{detail.explanation.summary}</p></div></div><dl className="compact-facts"><div><dt>Evidence time</dt><dd>{time(detail.evidence_time)} UTC</dd></div><div><dt>Detector</dt><dd>Isolation Forest</dd></div><div><dt>Reference cohort rows</dt><dd>{number(detail.model.training_rows)}</dd></div></dl><button className="btn btn-primary full-width" onClick={onExplain}>Explore the evidence<ArrowUpRight size={16}/></button><button className="btn btn-secondary full-width" onClick={onMaintain}>View maintenance advisory</button></Panel></div>
<div className="analysis-lower"><Panel title="Anomaly risk through time" eyebrow="Detection timeline" action={<Gauge size={17} className="muted"/>}><SensorChart points={detail.points} score/></Panel><Panel title="Sensor evidence" eyebrow="Reference comparison"><div className="sensor-evidence-list">{detail.features.map(f=><button key={f.key} className={`sensor-evidence-row ${f.key===feature?.key?'selected':''}`} onClick={()=>setChosen(f.key)}><span className="sensor-evidence-icon"><Activity size={16}/></span><span className="sensor-evidence-name"><strong>{f.label}</strong><small>{f.missing_count?`${f.missing_count} missing readings`:'Valid readings available'}</small></span><span className="sensor-evidence-value"><strong>{number(f.latest,2)} <small>{f.unit}</small></strong><small>{f.deviation==null?'Deviation unavailable':`${number(f.deviation,1)} × robust deviation`}</small></span></button>)}</div></Panel></div>
<Note>Markers identify unusual observations, not confirmed faults. Missing readings remain visible as gaps. The first detected anomaly is an observed onset, not the time a physical fault began.</Note>
</>;}
