'use client';
import { ArrowUpRight, Braces, Check, CircleHelp, Cpu, FlaskConical, GitBranch, Info, Layers3, ShieldCheck, Sparkles } from 'lucide-react';
import type { Dashboard, Detail } from '@/lib/types';
import { number, time } from '@/lib/utils';
import { EmptyState, Note, Panel, ScoreRing, StatusBadge } from '@/components/ui';

export default function Explanation({detail,dashboard,onMaintain}:{detail:Detail;dashboard:Dashboard;onMaintain:()=>void}) {const sorted=[...detail.features].sort((a,b)=>b.contribution-a.contribution);const max=Math.max(...sorted.map(f=>f.contribution),.001);const evaluation=dashboard.evaluation;return <>
<div className="explanation-grid"><Panel title="From signal to understanding" eyebrow="Evidence synthesis" action={<span className="quiet-chip"><Braces size={12}/>Deterministic reasoning</span>} className="reasoning-panel"><div className="reasoning-head"><span className="reasoning-orb"><Sparkles size={25}/></span><div><StatusBadge status={detail.status}/><h2>{detail.explanation.title}</h2></div></div><p className="reasoning-summary">{detail.explanation.summary}</p><div className="cause-box"><div className="eyebrow">Possible explanation</div><p>{detail.explanation.possible_cause}</p><span><Info size={12}/>A hypothesis for inspection, not a verified diagnosis.</span></div><div className="evidence-steps">{detail.explanation.evidence.map((e,i)=><div key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{e}</p><Check size={14}/></div>)}</div><div className="reasoning-footer"><span><ShieldCheck size={14}/>Grounded in this dataset</span><span>{time(detail.evidence_time,true)} UTC</span></div></Panel>
<Panel title="What drives the indication?" eyebrow="Sensor attribution" action={<Layers3 size={17} className="muted"/>}><p className="panel-description">Relative sensitivity share (%) when each sensor is replaced with its reference value. This measures score influence, not diagnostic confidence.</p><div className="attribution-list">{sorted.map((f,i)=><div className="attribution-row" key={f.key}><div><span className="attribution-number">{String(i+1).padStart(2,'0')}</span><strong>{f.label}</strong><span className="mono">{f.latest==null||f.baseline==null||detail.model.training_rows===0?'Unavailable':`${number(f.contribution,1)}%`}</span></div><div className="attribution-track"><i style={{width:`${f.latest==null||f.baseline==null||detail.model.training_rows===0?0:Math.max(0,f.contribution/max)*100}%`}}/></div><div className="attribution-values"><span>Evidence {number(f.latest,2)} {f.unit}</span><span>Reference {number(f.baseline,2)} {f.unit}</span></div></div>)}</div><Note>{detail.explanation.method}</Note></Panel></div>
<div className="explanation-lower"><Panel title="Model evaluation" eyebrow="Measured, with context" action={<span className="quiet-chip"><FlaskConical size={13}/>{dashboard.dataset.source==='synthetic'?'Synthetic benchmark':'Dataset evaluation'}</span>}><p className="panel-description">{evaluation.context}</p>{evaluation.available?<div className="table-scroll"><table className="evaluation-table"><thead><tr><th>Detector</th><th>ROC-AUC</th><th>Precision</th><th>Recall</th><th>F1</th></tr></thead><tbody>{evaluation.models.map((m,i)=><tr key={m.name}><td><span className={`model-dot ${i?'baseline':''}`}/><strong>{m.name}</strong>{i===0&&<span className="tiny-label">PRIMARY</span>}</td><td>{number(m.auc,3)}</td><td>{m.precision==null?'—':`${number(m.precision*100,1)}%`}</td><td>{m.recall==null?'—':`${number(m.recall*100,1)}%`}</td><td>{number(m.f1,3)}</td></tr>)}</tbody></table></div>:<EmptyState title="Evaluation unavailable" icon={<FlaskConical size={26}/>}>{evaluation.note}</EmptyState>}{evaluation.available&&<Note>{evaluation.note}</Note>}<details className="model-details"><summary><Cpu size={14}/>Training and reproducibility<GitBranch size={14}/></summary><dl className="compact-facts"><div><dt>Algorithm</dt><dd>{detail.model.algorithm}</dd></div><div><dt>Implementation</dt><dd>{detail.model.version}</dd></div><div><dt>Reference rows</dt><dd>{number(detail.model.training_rows)}</dd></div><div><dt>Monitoring rows</dt><dd>{number(detail.model.validation_rows)}</dd></div><div><dt>Measured fit time</dt><dd>{number(detail.model.training_ms,0)} ms</dd></div><div><dt>Result source</dt><dd>{detail.model.cache_hit?'Reused cached analysis':'Fitted analysis'}</dd></div></dl><p>{detail.model.methodology}</p></details></Panel>
<Panel title="The next informed action" eyebrow="Maintenance handoff" className="next-action-panel"><div className="action-glyph"><ShieldCheck size={26}/></div><h3>{detail.explanation.recommendation}</h3><p>{detail.explanation.timeframe}</p><button className="btn btn-primary full-width" onClick={onMaintain}>Open maintenance advisory<ArrowUpRight size={16}/></button><div className="limitations"><strong>Evidence limitations</strong>{detail.explanation.limitations.map((l,i)=><p key={i}><CircleHelp size={12}/>{l}</p>)}</div></Panel></div>
</>;}
